version: "3"
services:
  yt4j-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: yt4j-mysql
    image: yt4j-mysql
    ports:
      - 3306:3306
    command: --lower_case_table_names=1
  yt4j-es:
    image: elasticsearch
    container_name: yt4j-es
    restart: always
    ports:
    - 9200:9200
    - 9300:9300
  yt4j-redis:
    container_name: yt4j-redis
    image: redis
    restart: always
    ports:
      - 6379:6379
  yt4j-sys:
    build:
      context: ./yt4j-modules/yt4j-sys
    image: yt4j-sys
    container_name: yt4j-sys
    restart: always
    ports:
      - 9100:9100
    depends_on:
      - yt4j-mysql
