spring:
  datasource:
    url: jdbc:mysql://rm-8vb6qoj0m6hmw9925go.mysql.zhangbei.rds.aliyuncs.com:3306/yt4j?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: shichenyang
    password: ENC(TOwx34XGDU5MZuBsaAur7ouBL5mlDd9z)
  redis:
    host: 39.99.213.137
    database: 2
    port: 8848
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
yt4j:
  jwt:
    filter:
      ignored-url:
        - /doc.html
        - /swagger-ui.html
        - /swagger-resources/**
        - /swagger/**
        - /**/v2/api-docs
        - /**/*.js
        - /**/*.css
        - /**/*.png
        - /**/*.ico
        - /webjars/springfox-swagger-ui/**
        - /actuator/**
      header: 'Access-Token'
      token-head: ''
  swagger:
    enabled: true
server:
  port: 9997