version: "3"
services:
  yt4j-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: yt4j-mysql
    image: yt4j-mysql
    ports:
      - "3306:3306"
    command: --lower_case_table_names=1
  yt4j-nacos:
    image: nacos/nacos-server:latest
    container_name: yt4j-nacos
    env_file:
      - ./nacos/nacos-standlone-mysql.env
    volumes:
      - ./nacos/logs:/home/nacos/logs
      - ./nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
    restart: always
    depends_on:
      - yt4j-mysql
  yt4j-redis:
    container_name: yt4j-redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
  yt4j-gateway:
    build:
      context: ../yt4j-gateway
    image: yt4j-gateway
    container_name: yt4j-gateway
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - yt4j-nacos
  yt4j-sys:
    build:
      context: ../yt4j-modules/yt4j-sys
    image: yt4j-sys
    container_name: yt4j-sys
    restart: always
    ports:
      - "9100:9100"
    depends_on:
      - yt4j-nacos
networks:
  default:
    external:
      name: yt4j
