version: "3"
services:
  yt4j-mysql:
    image: mysql/mysql-server:8.0.30
    container_name: yt4j-mysql
    volumes:
      - ./conf/mysql/my.cnf:/etc/my.cnf
      - ./data/mysql/data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    privileged: true
    network_mode: "host"
    restart: always
    command:
      --lower_case_table_names=1
  yt4j-nacos:
    image: nacos/nacos-server:v2.3.0
    container_name: yt4j-nacos
    environment:
      - JVM_XMS=256m
      - JVM_XMX=512m
    env_file:
      - ./conf/nacos/nacos-standlone-mysql.env
    volumes:
      - ./logs/nacos:/home/nacos/logs
    privileged: true
    network_mode: "host"
    restart: always
    depends_on:
      - yt4j-mysql
  yt4j-job:
    image: xuxueli/xxl-job-admin:2.4.0
    container_name: yt4j-job
    volumes:
      - ./logs/xxl-job:/data/applogs/xxl-job/
    environment:
      PARAMS: '--spring.datasource.url=jdbc:mysql://127.0.0.1:3306/xxl_job?Unicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=root'
    restart: always
    network_mode: "host"
    depends_on:
      - yt4j-nacos
  yt4j-redis:
    image: redis:latest
    container_name: yt4j-redis
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      - ./conf/redis/redis.conf:/etc/redis.conf
      - ./data/redis:/redis/data
    network_mode: "host"
    command: [ "redis-server", "/etc/redis.conf" ]
    restart: always
    privileged: true
  yt4j-minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # 管理后台用户名
      MINIO_ROOT_USER: admin
      # 管理后台密码，最小8个字符
      MINIO_ROOT_PASSWORD: admin123
      # https需要指定域名
      #MINIO_SERVER_URL: "https://xxx.com:9000"
      #MINIO_BROWSER_REDIRECT_URL: "https://xxx.com:9001"
      # 开启压缩 on 开启 off 关闭
      MINIO_COMPRESS: "off"
      # 扩展名 .pdf,.doc 为空 所有类型均压缩
      MINIO_COMPRESS_EXTENSIONS: ""
      # mime 类型 application/pdf 为空 所有类型均压缩
      MINIO_COMPRESS_MIME_TYPES: ""
    volumes:
      # 映射当前目录下的data目录至容器内/data目录
      - ./data/minio:/data
      # 映射配置目录
      - ./conf/minio:/root/.minio/
    command: server --address ':9000' --console-address ':9001' /data  # 指定容器中的目录 /data
    privileged: true
    network_mode: "host"



