spring:
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
      connection-timeout: 10s
      username:
      password:
logging:
  level:
    org.springframework.data.elasticsearch.core: debug
