spring:
  cloud:
    gateway:
      routes:
        - id: yt4j-sys
          uri: lb://yt4j-sys
          predicates:
            - Path=/sys/**
          filters:
            - StripPrefix=1
        - id: yt4j-auth
          uri: lb://yt4j-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: yt4j-crm
          uri: lb://yt4j-crm
          predicates:
            - Path=/crm/**
          filters:
            - StripPrefix=1
--- # 聚合文档
knife4j:
  # 聚合swagger文档
  gateway:
    enable: true
    routes:
      - name: 系统服务
        url: /sys/v3/api-docs
        service-name: sys
        order: 1
      - name: 鉴权服务
        url: /auth/v3/api-docs
        service-name: auth
        order: 2
