server:
  port: 8888
spring:
  application:
    name: @artifactId@
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    nacos:
      discovery:
        server-addr: yt4j-nacos:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - optional:nacos:application.yml
      - optional:nacos:${spring.application.name}.yml
