spring:
  datasource:
    url: jdbc:mysql://rm-8vb6qoj0m6hmw9925go.mysql.zhangbei.rds.aliyuncs.com:3306/yt4j?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(WEey6eY21y9PYNXv41lMmHq8zhgTJHwL)
    password: ENC(qDDILeH3CED3qGjfbtxb9v4OBapq9w8g)
  redis:
    host: 39.99.213.137
    port: 8848
    database: 2
yt4j:
  jwt:
    filter:
      ignored-url:
        - /sys/user/login
      header: 'Access-Token'
      token-head: ''
  swagger:
    enabled: false
server:
  port: 9999

jasypt:
  encryptor:
    password: yt4j