spring:
  datasource:
    url: jdbc:mysql://rm-8vb6qoj0m6hmw9925go.mysql.zhangbei.rds.aliyuncs.com:3306/yt4j?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: shichenyang
    password: '!Shijie123456'
  redis:
    host: 10.10.11.2
    database: 2
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
yt4j:
  jwt:
    filter:
      ignored-url:
        - /doc.html
        - /swagger-ui.html
        - /swagger-resources/**
        - /swagger/**
        - /**/v2/api-docs
        - /**/*.js
        - /**/*.css
        - /**/*.png
        - /**/*.ico
        - /webjars/springfox-swagger-ui/**
        - /actuator/**
        - /sys/user/login
      header: 'Access-Token'
      token-head: ''
  swagger:
    enabled: true
  rsa:
    private-key: 'MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJozY3W8y6mtqXMki3HdjgB+0lWHvwjws25Qa4qowXVgeLBgEeu9lenMS5Ga1MCtJo86XLBW3ahsLYW3yu4gPDtd+m3lKJjVjtoI41P8NEYaxQRqXqMaBPPGJQpPJ/IXjCv7S93sh6JMP+KqDg6qbf5awqbtlajNQbqxwbnv3xirAgMBAAECgYEAjPravjRER/e8asdIrmwPfih1CTm40OWwRvVDvVwYs8Xl0eujttJ4k27y0EasqRQlouGLCLYCpg9xd0XYROo35euwd3gR6rTJYxO3FaMXTQE5PS0SH9sxoizRZxehP6HPy6Y4ba4Ud81YF36pDWb5yujl6sH4rHEG/twpghZ/EIECQQDOS/tF3qscUd5oFJeo6RcDfW7BK1kG3tHP/wt8JZVrMcOQAA8v3Pwoa6BmQbAXNLjbZtmoGnib9BKv0zzus1VhAkEAv1o28Qqh5GPfMbaSuA1twf/Wx/lTF7sz/VP5+73pO/Irao1odaX74aPSd5zpARCSc29Nk0Kk5tGibDZ+/KvdiwJAOTU84y1SijHx2S8Mt5yb8y3PjuX0dEFKMcHqb20EuIs+TiqWC5Heo17lRjYlHOpT8RPefA2LMMRIglWz6gX1QQJAY3euxZ+kRgeQVtQz8k6wtj6aVDsLcXOTc+T6Nl0i51FcNjgpi7Zrd4BkAF9lU3Nc3XqHFbx34bApQR0W55sjPwJBAMTz13qfBjuEl7oiROiwUjKBHfLPBGv83zHh+5ppq1PjaZ8NjK7WIEPMqQPCz1ekS3YE+KVdu9UN/5LgqdeBqs0='
    public-key: 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCaM2N1vMupralzJItx3Y4AftJVh78I8LNuUGuKqMF1YHiwYBHrvZXpzEuRmtTArSaPOlywVt2obC2Ft8ruIDw7Xfpt5SiY1Y7aCONT/DRGGsUEal6jGgTzxiUKTyfyF4wr+0vd7IeiTD/iqg4Oqm3+WsKm7ZWozUG6scG5798YqwIDAQAB'
server:
  port: 9999