spring:
  datasource:
    url: jdbc:mysql://yt4j-mysql:3306/yt4j?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ENC(J4sCVXaoXyijS3Vf6vCqng==) #root
  redis:
    host: yt4j-redis
yt4j:
  jwt:
    filter:
      ignored-url:
        - /sys/user/login
      header: 'Access-Token'
      token-head: ''
  swagger:
    enabled: false
server:
  port: 9999

jasypt:
  encryptor:
    password: yt4j