server:
  port: 0
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: yt4j-nacos:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
      password: nacos
      username: nacos
  config:
    import:
      - optional:nacos:application.yml
      - optional:nacos:${spring.application.name}.yml
debug: true
