spring:
  datasource:
    url: jdbc:mysql://rm-8vb6qoj0m6hmw9925go.mysql.zhangbei.rds.aliyuncs.com:3306/yt4j?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: shichenyang
    password: '!Shijie123456'
  redis:
    host: 10.10.11.2
    database: 2
yt4j:
  jwt:
    filter:
      ignored-url:
        - /doc.html
        - /swagger-ui.html
        - /swagger-resources/**
        - /swagger/**
        - /**/v2/api-docs
        - /**/*.js
        - /**/*.css
        - /**/*.png
        - /**/*.ico
        - /webjars/springfox-swagger-ui/**
        - /actuator/**
        - /druid/**
        - /sysUser/login
  swagger:
    enable: true