server:
  port: 9100
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: yt4j-nacos:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:${spring.application.name}.yml

