spring:
  datasource:
    url: jdbc:mysql://yt4j-mysql:3306/yt4j-wx?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ENC(J4sCVXaoXyijS3Vf6vCqng==) #root
  redis:
    host: yt4j-redis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jasypt:
  encryptor:
    password: yt4j
